# Generated by Django 3.1.3 on 2020-12-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('pndg', 'pending'), ('fnsh', 'finished')], default='pndg', max_length=4),
        ),
    ]
